### ISSUE TITLE
誤字脱字・タイポ

### ISSUE THREAD

**Issue by ryo-endo** [scouty-inc/holacracy_constitution#16]
2.3 Duty of Prioritization (優先の義務)
    あらゆるの義務
    解消するする

3.2 Meeting Process (ミーティングプロセス)
    代わりのわりのプロセス

4.1.3 Get Authorization Before Spending Money (金銭を消費する前に承認を取ること)
    消費すること含まれます。

5.4.5 Integrative Decision-Making Process (統合意思決定プロセス)
    求めることがができ、

5.5.2 Process Restoration (プロセス復旧)
    プロセスが復元されたととき、

**Comment by nunukim** [comment]
https://github.com/lapras-inc/holacracy_constitution/pull/21
https://github.com/lapras-inc/holacracy_constitution/pull/20
https://github.com/lapras-inc/holacracy_constitution/pull/19
https://github.com/lapras-inc/holacracy_constitution/pull/18
https://github.com/lapras-inc/holacracy_constitution/pull/17
https://github.com/lapras-inc/holacracy_constitution/pull/15
これらで対応済み
